### ISSUE TITLE
Lead Feedback API Endpoints

### ISSUE THREAD

**Issue by SwarnimWalavalkar** [covidarmy/backend#36] opened 2021-05-03 14:10 UTC
Expose an endpoint to enable Users to provided feedback regarding the leads being shown on the website so we can refine our dataset.

We can have the following prompts on the frontend. These prompts can pop up when user clicks the phone number being shown in the lead and goes to the teleprompting screen. Once they come back we can show these in the popup.

> Helpful: if they pick up and say that they have stock
> 
> Unresponsive: if the number is out of reach, busy or did not pick up
> 
> Out Of Stock: if they don’t have any more of the resource type available
> 
> Invalid: if the number is wrong and they are not providing the selected resource type

## Database Schema
An object with the key as being one of the statues above, with an integer as the value representing the number of votes for each status eg.
```json
{
"helpful": 4,
"unresponsive": 1,
"nostock": 0,
"invalid": 0
}
```

**Comment by Utkarshbhimte** [comment] 2021-05-03 17:27
How will you prevent the same person from marking the resource twice?

and what if they change the status afterward, then we would have to decrease the count from prev status as well and increase in the current one.

**Comment by Utkarshbhimte** [comment] 2021-05-03 17:28
Also, let's move this to discussion first and then bring it when finalized

**Comment by rgxai** [comment] 2021-05-03 17:31
Should we maintain a score or should we just maintain the last 5 recent statuses for the lead? Last 5 because that would average out the result and give us more context compared to just one status. Can help us build some sort of scoring mechanism.

**Comment by arn4v** [comment] 2021-05-03 17:39
@Utkarshbhimte Since we're not doing authentication, local storage is the only way to keep track of the users vote on a resource. What downsides would there be to increasing/decreasing as the user changes their vote?

@rgxai I'm fine e

**Comment by rgxai** [comment] 2021-05-03 17:55
@arn4v yes that makes sense to me. however, the problem is that if last 5 have marked it as busy and not working, showing it to the 6th user is pointless and we should move it into cool down mode. if we keep a score and have an array like the following

```
{
"helpful": 2,
"unresponsive": 5,
"nostock": 1,
"invalid": 1
}

```

Then it gives us no meaningful data actually. We will have to build a logic for each prompt separately. For example, after how many invalid prompts do we remove the number from our DB all-together? After how many helpful prompts should we cycle the number and not show it to more folks in order to load balance the demand and supply? which is why I think having the last 5 would be a better approach because we can assume the number will come in again through a new tweet later and for every tweet containing the same number we can bump the status to helpful for the time being.

**Comment by Utkarshbhimte** [comment] 2021-05-03 17:58
@arn4v 
> What downsides would there be to increasing/decreasing as the user changes their vote?
If there user marks it as busy first, we will do busy++ and then mark it as helpful afterward, then helpful++
the count for both is the same now, hard to rank this now.

I like @rgxai's average for last n reviews approach. 

> Since we're not doing authentication, local storage is the only way to keep track of the users vote on a resource
I don't think that a reliable source of truth

**Comment by Utkarshbhimte** [comment] 2021-05-03 18:00
> we should store a score for each status, last 5 will skew in favor of not working or busy if the number is being called by 100s of people every minute.


@arn4v It's not a simple number ranking, busy means cooldown for 5 minutes, out of stock means cooldown for a couple of days, "invalid" means "blacklisting". Does this make sense?

**Comment by Utkarshbhimte** [comment] 2021-05-03 18:01
I think we need to store a calculated cooldown timestamp for resources.

**Comment by arn4v** [comment] 2021-05-03 18:02
> I don't think that a reliable source of truth

@Utkarshbhimte What approach can we take that isn't login auth?

**Comment by rgxai** [comment] 2021-05-03 18:09
I don't think we need to worry about auth as the data is dynamically changing and the possibility of one user modifying a number's status to game the system multiple times is quite rare. the average of last n prompts should take care of that problem in my opinion as more users leave their feedback on it. and if it marked as invalid by multiple folks, we can simply discard that number all together. we already have a semi verification layer built in through the heavily refined twitter search query.

**Comment by Utkarshbhimte** [comment] 2021-05-03 18:10
> I don't think we need to worry about auth as the data is dynamically changing and the possibility of one user modifying a number's status to game the system 

I don't think it would be to game the system, but just to update the status with positive intensions.

**Comment by Utkarshbhimte** [comment] 2021-05-03 18:13
> we already have a semi verification layer built-in through the heavily refined twitter search query.

Sadly, Still it's not working for most of the people reaching out to me on my Twitter DMs 😔

**Comment by rgxai** [comment] 2021-05-03 18:21
So my assumption is that Twitter filters out 50-60% of the incorrect leads and provides a real time source. To filter out the working 5% from this 50% would mostly be manual and volunteer approach. I don't see any problems with that..

**Comment by Utkarshbhimte** [comment] 2021-05-03 18:24
I agree, we do have a good input channel, we should start working towards improving the quality now. 😊

**Closed** 2021-05-07 13:18 UTC
Labels: enhancement
